telegram:
    bot1:
        token: 583120681:AAFbhhq2ph5qS7c6I9joz_MqViWEl2TEpx0
        owner: user

users:
    k.bashevoy: chat_id (583120681)
    default: 0

stickers:
    default: CAADAgADOQEAAjbsGwVonn-MGIBY3AI
    success: CAADAgADQAADyIsGAAE7MpzFPFQX5QI
